server:
  port: 443
  ssl:
    key-store: classpath:client.pfx
    key-store-type: PKCS12
    key-store-password: 123456
web:
  upload-path: d:/myfile/upload
  front-path: d:/myfile/front
spring:
  datasource:
    #mysql5 中com.mysql.jdbc.Driver
    #mysql6 中com.mysql.cj.jdbc.Driver  注意连接时需要指定时区serverTimezone
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fangdichan?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations : classpath:/static/,file:${web.upload-path},file:${web.front-path}
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: classpath:/templates/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  thymeleaf:
    cache: false
  template:
    cache: false
  mvc:
    favicon:
      enabled: false
mybatis:
  #扫描classpath中mapper目录下的映射配置文件，针对与映射配置文件放到了resource目录下
  mapper-locations: classpath:mapper/*.xml
  #标签作用mapper.xml中返回pojo时不需要写包名，直接写对象名即可
  type-aliases-package: com.bz.bean

thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5
